baseURL = "https://danielpygo.github.io/"
languageCode = "en-us"
title = "Daniel Moore's Website"
theme = "hyde-hyde"
[params.social]
    github = "danielpygo"
    linkedin = "daniel-moore-07962b104"
    twitter = "dan_moore_10x"
    email = "ddmoorish@gmail.com"
[params]
    themeColor = "theme-base-08"
    author = "Daniel Moore"
    title = "Daniel Moore's website and blog"
    description = "The game begat the player"
    authorimage = "daniel.jpg"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    paginate = 5
[[menu.main]]
    name = "Personal"
    identifier = "personal"
    weight = 100
    url = "/personal/"
[[menu.main]]
    name = "Programming"
    identifier = "programming"
    weight = 100
    url = "/programming/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 100
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "Notes"
    weight = 100
    identifier = "notes"
    url = "/notes/"
[[menu.main]]
    name = "Quotes"
    weight = 100
    identifier = "quotes"
    url = "/quotes/"
